version: '3.9'


volumes:
  pg_data: {}

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${PG_DATABASE:-danny}
      POSTGRES_USER: ${PG_USER:-danny}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-danny}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER:-danny}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports: 
    - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
